window.discipuladoLessons = [
  {
    "slug": "intro",
    "title": "Introducción al Discipulado",
    "content": "::intro-lead::\n::intro-cards::\n::overview-table::\n::agenda::"
  },
  {
    "slug": "semana-1",
    "title": "Semana 1 – El Evangelio: La Base de Todo",
    "content": "📜 Lectura Bíblica:\nEfesios 2:1–10\nJuan 3:16\nRomanos 5:6–11\n🎯 Objetivo:\nEntender que la salvación es un regalo de Dios por gracia mediante la fe, no por obras. El\ndiscípulo debe identificar su nueva identidad en Cristo y poder explicar el evangelio con\nclaridad.\n🗣️ Preguntas de Discusión:\n1.  ¿Qué dice Efesios 2 sobre nuestra condición antes de conocer a Cristo?\n2.  ¿Qué significa “por gracia sois salvos por medio de la fe”?\n3.  ¿Cómo explicarías el evangelio a un amigo en 1 minuto?\n4.  ¿Qué diferencia ha hecho Cristo en tu vida desde tu conversión?\n📝 Actividad práctica:\nEscribe tu testimonio en tres partes:\n1.  Antes de Cristo\n2.  Cómo conociste a Cristo\n3.  Tu vida ahora con Cristo\nCompártelo oralmente con tu discipulador.\n📌 Versículo para memorizar:\n“Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús\nSeñor nuestro.” —Romanos 6:23\n🛠️ Desafío de la semana:\nOra por tres personas que aún no conocen a Cristo. Anota sus nombres. Pide a Dios la\noportunidad de compartir tu testimonio con al menos una de ellas.\n👥 Para reproducir esta lección:\nUsa las mismas lecturas bíblicas\nPregunta al nuevo discípulo: ¿Cuál es tu historia? ¿Dónde estás tú en relación con Dios?\nAyúdalo a escribir su testimonio.\nMemoriza juntos Romanos 6:23."
  },
  {
    "slug": "semana-2",
    "title": "Semana 2: ¿Qué es un discípulo?",
    "content": "📜 Lectura Bíblica:\nMateo 4:18–22\nLucas 9:23–25\nJuan 8:31–32\n🌟 Objetivo:\nComprender el llamado de Cristo a ser sus seguidores, no solo creyentes. Un discípulo es\nalguien que aprende de Jesús, lo imita y se somete a su señorío cada día.\n🚩 Preguntas para reflexión:\n1.  ¿Cuál fue el llamado que Jesús hizo a Pedro, Andrés, Jacobo y Juan en Mateo 4?\n2.  ¿Qué significa \"tomar tu cruz cada día\"?\n3.  ¿En qué áreas de tu vida estás luchando con negarte a ti mismo?\n4.  ¿Estás viviendo como simple creyente o como verdadero discípulo?\n📄 Actividad:\nComienza un diario devocional de 5 días, anotando:\nLo que leíste\nLo que Dios te habló\nCómo puedes obedecer esa Palabra\n👌 Versículo para memorizar:\n\"Y decía a todos: Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz cada\ndía, y sígame.\" — Lucas 9:23\n🔧 Desafío de la semana:\nToma una decisión concreta que implique negarte a ti mismo por obedecer a Cristo (ej.\nperdonar, servir, cambiar una prioridad, dedicar tiempo a orar o leer la Biblia).\n👥 Para reproducir esta lección:\nPide al nuevo discípulo que lea Mateo 4 y Lucas 9 contigo\nPregunta: ¿Qué te impide seguir a Cristo con todo?\nAyúdalo a establecer una rutina devocional sencilla\nMemoricen juntos Lucas 9:23"
  },
  {
    "slug": "semana-3",
    "title": "Semana 3 – La Palabra de Dios",
    "content": "📜 Lectura Bíblica:\n2 Timoteo 3:14–17\nHebreos 4:12\nSalmo 119:105\n🎯 Objetivo:\nReconocer que la Biblia es la Palabra inspirada por Dios, útil para enseñar, corregir y formar al\ncreyente. Aprender a leerla diariamente con propósito y aplicarla a la vida.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué dice la Biblia acerca de su propia utilidad?\n2.  ¿Cómo ha impactado tu vida la lectura de la Palabra de Dios?\n3.  ¿Por qué es necesario desarrollar el hábito diario de la Escritura?\n4.  ¿Qué parte de la Biblia te resulta más difícil de comprender o aplicar?\n📔 Actividad:\nComienza a usar el método H.E.A.R. para estudiar la Biblia. Este método incluye:\nH (Highlight): Resalta un versículo clave del pasaje\nE (Explain): Explica el contexto y significado\nA (Apply): Aplica esa verdad a tu vida\nR (Respond): Escribe una oración o compromiso en respuesta\nHaz este ejercicio con 2 Timoteo 3:16 esta semana.\n📌 Versículo para Memorizar:\n“Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para\ninstruir en justicia.” —2 Timoteo 3:16\n🛠️ Desafío de la Semana:\nAparta al menos 15 minutos al día para leer un pasaje bíblico y aplicar el método H.E.A.R. por\n3 días consecutivos. Comparte con tu discipulador lo que aprendiste.\n👥 Para reproducir esta lección:\nEnseña el método H.E.A.R. con un ejemplo simple (como Juan 15 o Salmo 1).\nAnima a tu discípulo a comenzar con el evangelio de Marcos.\nPractiquen juntos una lectura devocional de 10 minutos.\nMemoricen 2 Timoteo 3:16 juntos."
  },
  {
    "slug": "semana-4",
    "title": "Semana 4 – La Oración",
    "content": "📜 Lectura Bíblica:\nMateo 6:5–13\nFilipenses 4:6–7\nSalmo 145:18\n🎯 Objetivo:\nEntender la oración como una conversación íntima con Dios, basada en confianza y\nreverencia. Aprender a orar diariamente con estructura y sinceridad.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué enseña Jesús sobre cómo no debemos orar?\n2.  ¿Qué estructura sugiere la oración modelo (el Padre Nuestro)?\n3.  ¿Qué cargas puedes entregar a Dios esta semana?\n4.  ¿Sientes que escuchas a Dios al orar? ¿Por qué?\n📔 Actividad:\nCrea una hoja de oración personal con 4 columnas:\nAdoración (quién es Dios)\nConfesión (pecados que necesitas reconocer)\nAcción de gracias (cosas por las que das gracias)\nPeticiones (cosas que necesitas pedir)\nUsa esta hoja para orar cada día al menos 5 minutos.\n📌 Versículo para Memorizar:\n“Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda\noración y ruego, con acción de gracias.” —Filipenses 4:6\n🛠️ Desafío de la Semana:\nOra diariamente usando tu hoja de oración. Compártela con tu discipulador. Escribe al final\nde la semana una respuesta de Dios a tus oraciones.\n👥 Para Reproducir:\nEnséñale a tu discípulo el modelo de oración de Mateo 6.\nPractiquen orar juntos en voz alta.\nAnímenlo a escribir y orar con su hoja diaria.\nMemoricen Filipenses 4:6 juntos."
  },
  {
    "slug": "semana-5",
    "title": "Semana 5 – La Iglesia",
    "content": "📜 Lectura Bíblica:\nHechos 2:42–47\nHebreos 10:24–25\n1 Corintios 12:12–27\n🎯 Objetivo:\nComprender que la iglesia es la familia espiritual de Dios, donde el creyente crece, sirve y es\nprotegido. Ser parte activa de la iglesia local es esencial para la vida cristiana.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué hacían los primeros cristianos según Hechos 2?\n2.  ¿Qué significa “no dejar de congregarse”?\n3.  ¿Por qué necesitamos a otros creyentes?\n4.  ¿Cómo puedes usar tus dones en tu iglesia local?\n📔 Actividad:\nHaz una lista de razones por las que agradeces tu iglesia.\nHabla con tu pastor o líder sobre una forma concreta de comenzar a servir esta semana\n(ej. limpieza, bienvenida, oración, apoyo a otro creyente).\n📌 Versículo para Memorizar:\n“Y considerémonos unos a otros para estimularnos al amor y a las buenas obras; no dejando\nde congregarnos…” —Hebreos 10:24–25a\n🛠️ Desafío de la Semana:\nAsiste fielmente a los cultos de tu iglesia. Participa en una reunión de oración o grupo\npequeño. Identifica un área de servicio y comienza esta semana.\n👥 Para Reproducir:\nLee Hechos 2 y 1 Corintios 12 con tu discípulo.\nPregunta: ¿Cómo puedes ser parte activa del cuerpo de Cristo?\nAyúdalo a hablar con un líder de su iglesia para comenzar a servir.\nMemoricen juntos Hebreos 10:24–25."
  },
  {
    "slug": "semana-6",
    "title": "Semana 6 – Tentación y Santidad",
    "content": "📜 Lectura Bíblica:\n1 Corintios 10:12–13\nSantiago 4:7–10\n1 Pedro 1:14–16\n🎯 Objetivo:\nAprender a resistir la tentación con la ayuda del Espíritu Santo y crecer en santidad práctica.\nComprender que la santidad es el llamado de todo creyente, no solo de líderes.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué promesa nos da Dios en 1 Corintios 10:13?\n2.  ¿Qué dice Santiago sobre la secuencia: someterse a Dios → resistir al diablo?\n3.  ¿Cómo entiendes el mandato “sed santos, porque yo soy santo”?\n4.  ¿Qué tentaciones enfrentas con mayor frecuencia?\n📔 Actividad:\nIdentifica una tentación frecuente en tu vida.\nEscribe un “Plan de escape espiritual” que incluya:\nUn versículo que memorizarás\nUn hábito que reemplazará la tentación\nUna persona con quien rendirás cuentas\n📌 Versículo para Memorizar:\n“No os ha sobrevenido ninguna tentación que no sea humana… pero fiel es Dios, que no os\ndejará ser tentados más de lo que podéis resistir.” —1 Corintios 10:13\n🛠️ Desafío de la Semana:\nAplica tu plan cuando enfrentes tentación. Habla con tu discipulador sobre tu progreso y\nlucha. Ora cada mañana por santidad.\n👥 Para Reproducir:\nComparte tu testimonio de victoria sobre una tentación.\nEnseña a tu discípulo a identificar, reemplazar y resistir.\nOren juntos por pureza.\nMemoricen 1 Corintios 10:13."
  },
  {
    "slug": "semana-7",
    "title": "Semana 7 – El Espíritu Santo",
    "content": "📜 Lectura Bíblica:\nRomanos 8:1–17\nGálatas 5:16–25\nJuan 14:16–17\n🎯 Objetivo:\nEntender que el Espíritu Santo no solo mora en el creyente, sino que lo capacita para vivir,\nvencer y servir. Aprender a caminar en el Espíritu y discernir su guía.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué significa “andar en el Espíritu”?\n2.  ¿Cuál es la diferencia entre las obras de la carne y el fruto del Espíritu?\n3.  ¿Dónde has visto al Espíritu Santo actuar en tu vida?\n4.  ¿Le das espacio al Espíritu para guiar tus decisiones?\n📔 Actividad:\nLee Gálatas 5:22–23 y subraya los frutos que ves en tu vida.\nEscoge uno que quieras cultivar intencionalmente esta semana.\nOra diariamente: “Espíritu Santo, lléname y guíame hoy.”\n📌 Versículo para Memorizar:\n“Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe,\nmansedumbre, templanza...” —Gálatas 5:22–23\n🛠️ Desafío de la Semana:\nHaz un diario breve donde anotes cómo experimentaste al Espíritu Santo cada día. Ej: una\nconvicción, una decisión guiada, una victoria espiritual.\n👥 Para Reproducir:\nComparte cómo conociste al Espíritu Santo.\nAyuda a tu discípulo a identificar su lucha entre carne y Espíritu.\nMemoricen juntos Gálatas 5:22–23.\nOren pidiendo el fruto del Espíritu."
  },
  {
    "slug": "semana-8",
    "title": "Semana 8 – Servicio",
    "content": "📜 Lectura Bíblica:\nGálatas 5:13\n1 Pedro 4:10–11\nMarcos 10:42–45\n🎯 Objetivo:\nEntender que todo creyente ha sido llamado a servir como expresión del amor cristiano y del\ncarácter de Cristo. Descubrir cómo usar nuestros dones espirituales para edificar a la iglesia.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué actitud enseñó Jesús sobre el liderazgo y el servicio?\n2.  ¿Qué significa servir “conforme al poder que Dios da”?\n3.  ¿Qué habilidades o dones tienes que podrías usar para bendecir a otros?\n4.  ¿Cómo puede el servicio fortalecer tu fe?\n📔 Actividad:\nHaz una lista de áreas prácticas donde podrías servir en tu iglesia o comunidad esta\nsemana (ej. limpieza, oración, enseñanza, visitar, ayudar).\nEscoge una y actúa.\n📌 Versículo para Memorizar:\n“Cada uno según el don que ha recibido, minístrelo a los otros, como buenos administradores\nde la multiforme gracia de Dios.” —1 Pedro 4:10\n🛠️ Desafío de la Semana:\nRealiza al menos un acto de servicio concreto. Luego, reflexiona: ¿cómo sentiste a Dios\nusándote?\n👥 Para Reproducir:\nPregunta a tu discípulo: ¿en qué podrías ayudar a otros?\nOren juntos para que Dios revele sus dones.\nAliéntalo a tomar acción esta semana.\nMemoricen 1 Pedro 4:10."
  },
  {
    "slug": "semana-9",
    "title": "Semana 9 – Evangelismo",
    "content": "📜 Lectura Bíblica:\nMateo 28:18–20\nRomanos 10:9–15\nHechos 1:8\n🎯 Objetivo:\nComprender el mandato de Jesús de hacer discípulos a todas las naciones. Aprender a\ncompartir el evangelio con claridad, convicción y amor.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué significa “hacer discípulos”? ¿Es solo para líderes?\n2.  ¿Por qué es necesario predicar el evangelio si la fe viene por el oír?\n3.  ¿Cuál es tu mayor temor al compartir tu fe?\n4.  ¿A quién conoces que necesita escuchar de Jesús?\n📔 Actividad:\nEscribe un bosquejo breve de cómo compartir el evangelio en 3 pasos:\n1.  La necesidad del hombre (pecado)\n2.  La obra de Cristo (cruz y resurrección)\n3.  La respuesta del oyente (arrepentimiento y fe)\nPrepara una oración para usar como guía cuando evangelices.\n📌 Versículo para Memorizar:\n“Por tanto, id, y haced discípulos a todas las naciones…” —Mateo 28:19a\n🛠️ Desafío de la Semana:\nOra por tres personas no creyentes por nombre. Busca una oportunidad para compartir tu\ntestimonio o el evangelio con al menos una.\n👥 Para Reproducir:\nEnseña a tu discípulo el bosquejo de evangelismo.\nHagan juntos una práctica de presentación en voz alta.\nAnímalo a invitar a alguien a la iglesia o a una reunión.\nMemoricen Mateo 28:19."
  },
  {
    "slug": "semana-10",
    "title": "Semana 10 – Rendición de Cuentas",
    "content": "📜 Lectura Bíblica:\nProverbios 27:17\nHebreos 3:12–14\nSantiago 5:16\n🎯 Objetivo:\nReconocer el valor de la rendición de cuentas entre hermanos en la fe. Aprender a cultivar\nrelaciones donde haya confesión, ánimo y corrección en amor para el crecimiento espiritual.\n🗣️ Preguntas para Reflexión:\n1.  ¿Por qué es difícil ser transparente con otros creyentes?\n2.  ¿Qué peligro corre un cristiano que camina solo?\n3.  ¿Qué significa “exhortarse cada día”?\n4.  ¿Tienes alguien que conozca tus luchas y te anime?\n📔 Actividad:\nIdentifica una persona madura en la fe con la que puedas tener rendición de cuentas\nsemanal.\nDefine con esa persona: día, frecuencia, temas clave (oración, lectura bíblica,\ntentaciones, decisiones).\n📌 Versículo para Memorizar:\n“Hierro con hierro se aguza; Y así el hombre aguza el rostro de su amigo.” —Proverbios 27:17\n🛠️ Desafío de la Semana:\nEstablece tu primera reunión de rendición. Sé intencional, honesto y perseverante.\n👥 Para Reproducir:\nModela apertura con tu discípulo (sin ser invasivo).\nAliéntalo a encontrar a alguien con quien caminar en la fe.\nHablen juntos sobre límites, respeto y verdad.\nMemoricen juntos Proverbios 27:17."
  },
  {
    "slug": "semana-11",
    "title": "Semana 11 – Formando Otros Discípulos",
    "content": "📜 Lectura Bíblica:\n2 Timoteo 2:2\nMateo 28:19–20\nJuan 15:16\n🎯 Objetivo:\nEntender que el discipulado no termina cuando uno crece espiritualmente, sino cuando\ncomienza a formar a otros. Aceptar el llamado de ser un multiplicador del Reino de Dios.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué significa “enseñar a otros que enseñen a otros”?\n2.  ¿Te sientes preparado para discipular? ¿Qué te falta?\n3.  ¿A quién podrías invitar a comenzar este camino contigo?\n4.  ¿Qué obstáculos necesitas superar para hacer discípulos?\n📔 Actividad:\nEscribe una lista de 1 a 3 personas en tu entorno que podrías invitar a ser discipuladas.\nOra por cada una esta semana. Piensa cómo y cuándo comenzarás.\n📌 Versículo para Memorizar:\n“Lo que has oído de mí ante muchos testigos, esto encarga a hombres fieles que sean\nidóneos para enseñar también a otros.” —2 Timoteo 2:2\n🛠️ Desafío de la Semana:\nHaz contacto con al menos una persona de tu lista y ofrece comenzar un proceso de\ndiscipulado.\n👥 Para Reproducir:\nComparte cómo te formó este proceso.\nHaz un plan con tu discípulo: a quién, cuándo, cómo discipular.\nOren juntos por fruto y fidelidad.\nMemoricen 2 Timoteo 2:2."
  },
  {
    "slug": "semana-12",
    "title": "Semana 12 – Vida y Misión",
    "content": "📜 Lectura Bíblica:\nHechos 1:8\nColosenses 3:23–24\nMateo 5:14–16\n🎯 Objetivo:\nComprender que el cristiano es un testigo de Cristo dondequiera que esté. Asumir la\nidentidad de embajador del Reino con integridad, pasión y propósito.\n🗣️ Preguntas para Reflexión:\n1.  ¿Qué significa ser un testigo “hasta lo último de la tierra”?\n2.  ¿Cómo puedes reflejar a Cristo en tu trabajo, familia o estudios?\n3.  ¿Cuál es tu mayor motivación en la vida? ¿Está alineada con el Reino?\n4.  ¿Qué te impide vivir intencionalmente para la misión de Dios?\n📔 Actividad:\nRedacta un “compromiso de misión personal” que incluya:\nCómo vivirás como discípulo\nCómo harás discípulos\nCómo servirás en tu iglesia\nCómo representarás a Cristo diariamente\n📌 Versículo para Memorizar:\n“Y me seréis testigos en Jerusalén, en toda Judea, en Samaria, y hasta lo último de la tierra.”\n—Hechos 1:8b\n🛠️ Desafío Final:\nHaz tu compromiso de misión en oración. Firma tu declaración. Comparte tu decisión con tu\ndiscipulador y tu iglesia local.\n👥 Para Reproducir:\nRevisa toda la guía con tu discípulo.\nFelicítalo y anímalo a comenzar con su primer discípulo.\nAyúdale a preparar una reunión de inicio.\nMemoricen Hechos 1:8 como su nuevo lema.\n📝"
  },
  {
    "slug": "compromiso",
    "title": "Notas Finales y Compromiso",
    "content": "Al llegar al final de este camino de 12 semanas, recuerda: el discipulado no es un curso, sino\nun estilo de vida. Jesús no nos llamó a aprender por aprender, sino a seguirle, vivir como Él, y\nformar a otros para que hagan lo mismo.\nCompromiso personal:\nDeclaro delante de Dios y de mi iglesia local que:\nReconozco a Jesucristo como mi Señor y Salvador.\nMe comprometo a vivir como discípulo fiel, guiado por el Espíritu Santo.\nMe dispongo a discipular a otros, enseñándoles lo que yo mismo he aprendido.\nBuscaré crecer continuamente en comunión, servicio, santidad y misión.\nFirma: ________________________\nFecha: ________________________\n📖"
  },
  {
    "slug": "versiculos",
    "title": "Versículos para Memorizar",
    "content": "Versículos para Memorizar (Resumen)\nAquí están los versículos clave que se han memorizado durante las 12 semanas. Puedes\nrepasarlos, meditarlos, y usarlos al discipular a otros:\n1.  Romanos 6:23 – El Evangelio\n2.  Lucas 9:23 – Seguir a Cristo\n3.  2 Timoteo 3:16 – La Palabra\n4.  Filipenses 4:6 – Oración\n5.  Hebreos 10:24–25 – Iglesia\n6.  1 Corintios 10:13 – Tentación\n7.  Gálatas 5:22–23 – Fruto del Espíritu\n8.  1 Pedro 4:10 – Servicio\n9.  Mateo 28:19 – Evangelismo\n10. Proverbios 27:17 – Rendición\n11.  2 Timoteo 2:2 – Multiplicación\n12. Hechos 1:8 – Misión\nSugerencia: Escribe estos versículos en tarjetas o app de memorización y repásalos\nsemanalmente.\n👥"
  },
  {
    "slug": "guia",
    "title": "Guía para Discipular a Otros",
    "content": "Guía para Discipular a Otros (Modelo Reproducible)\n¿Cómo iniciar?\n1.  Ora: Pide a Dios dirección sobre a quién discipular.\n2.  Invita: Acércate personalmente. Sé claro y amable.\n3.  Reúne: Acuerden un lugar, día y hora semanal.\n4.  Usa esta guía: Aplica cada lección según el ritmo de tu discípulo.\nEstructura de cada reunión (1 hora aprox.):\n1.  Saludo y oración inicial (5 min)\n2.  Revisión de la tarea anterior (10 min)\n3.  Lectura bíblica y enseñanza (25 min)\n4.  Preguntas y diálogo (15 min)\n5.  Oración final y asignación (5 min)\nRecomendaciones:\nSé paciente, constante y lleno de gracia.\nComparte tu propia vida, no solo conocimiento.\nHaz seguimiento y anima. El discipulado es relación, no solo información.\nMotiva a tu discípulo a discipular a otros tan pronto esté listo.\n“El que permanece en mí, y yo en él, éste lleva mucho fruto…” —Juan 15:5"
  }
];
