window.romanos12Lessons = [
  {
    "slug": "clase-1",
    "label": "Clase 1",
    "title": "Una vida entregada a Dios",
    "subtitle": "La verdadera adoración es responder a las misericordias de",
    "pdfUrl": "./files/romanos-12/01-una-vida-entregada-a-dios.pdf",
    "paragraphs": [
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 1",
      "PRFWB",
      "ASOCIACIÓN BAUTISTA LIBRE DE PUERTO RICO",
      "UNA VIDA ENTREGADA A DIOS",
      "Romanos 12:1–2",
      "La verdadera adoración es responder a las misericordias de",
      "Dios entregándole toda nuestra vida.",
      "Estudio individual ? Clase grupal ? Guía del estudiante",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 2",
      "TEXTO BASE Romanos 12:1–2",
      "OBJETIVO Comprender que la entrega del creyente a Dios",
      "no busca conseguir su misericordia, sino que",
      "responde a la misericordia recibida en Cristo.",
      "1. Lee y observa",
      "Lea Romanos 12:1–2.",
      "Mientras lee, identifique las siguientes expresiones:",
      "“misericordias de Dios”",
      "“presentéis vuestros cuerpos”",
      "“sacrificio vivo”",
      "“no os conforméis”",
      "“transformaos”",
      "“renovación de vuestro entendimiento”",
      "Para descubrir",
      "1. ¿Qué pide Pablo que presentemos a Dios?",
      "2. ¿Qué características debe tener ese sacrificio?",
      "3. ¿Qué debemos rechazar según el v. 2?",
      "4. ¿Qué debe ser renovado?",
      "2. Comprendiendo el contexto",
      "La palabra “Así que” es indispensable para comprender el pasaje.",
      "Pablo no comienza Romanos 12 diciendo simplemente:",
      "“Entrégate más.”",
      "Primero ha dedicado once capítulos a explicar el evangelio.",
      "Considere algunas de las verdades que ya ha presentado:",
      "Romanos 3:23 — todos pecaron.",
      "Romanos 5:1 — somos justificados por la fe.",
      "Romanos 5:8 — Cristo murió por nosotros siendo aún pecadores.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 3",
      "Romanos 6:4 — somos llamados a andar en vida nueva.",
      "Romanos 8:1 — no hay condenación para quienes están en Cristo Jesús.",
      "Romanos 8:38–39 — nada puede separar al creyente del amor de Dios en Cristo.",
      "Después de todo esto, Pablo dice:",
      "“Así que… por las misericordias de Dios…”",
      "El orden es importante:",
      "MISERICORDIA → ENTREGA",
      "No:",
      "ENTREGA → MISERICORDIA",
      "El cristiano no entrega su vida para conseguir que Dios lo ame.",
      "Entrega su vida porque ha conocido el amor y la misericordia de Dios en Cristo.",
      "3. ¿Qué significa “sacrificio vivo”?",
      "En el Antiguo Testamento, el lenguaje de sacrificio estaba asociado con las ofrendas presentadas a",
      "Dios.",
      "Pero Pablo utiliza una expresión sorprendente:",
      "“Sacrificio vivo”",
      "El creyente continúa viviendo, pero ahora reconoce que toda su existencia pertenece a Dios.",
      "Por eso Pablo habla de presentar nuestros cuerpos.",
      "Esto incluye nuestra vida real y cotidiana:",
      " Lo que hacemos.",
      " Lo que miramos.",
      " Cómo hablamos.",
      " Cómo trabajamos.",
      " Cómo utilizamos nuestros recursos.",
      " Cómo tratamos a las personas.",
      " Cómo utilizamos nuestras capacidades.",
      "La adoración, por tanto, no ocurre solamente cuando cantamos en una iglesia.",
      "Toda una vida consagrada a Dios se convierte en adoración.",
      "4. El sacrificio de Cristo y nuestro sacrificio",
      "Aquí debemos hacer una distinción fundamental.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 4",
      "Lea Hebreos 10:10.",
      "Jesucristo ofreció su cuerpo “una vez para siempre”.",
      "Su sacrificio fue suficiente para tratar con nuestro pecado.",
      "Nuestro “sacrificio vivo” de Romanos 12:1 no añade nada a la obra de Cristo.",
      "Cristo se entregó para salvarnos.",
      "Nosotros nos entregamos porque Él nos salvó.",
      "Esta diferencia protege el evangelio.",
      "La salvación no se obtiene mediante nuestra consagración. Nuestra consagración es fruto de la",
      "gracia que hemos recibido.",
      "5. Una mente transformada",
      "Romanos 12:2 presenta un contraste:",
      "NO OS CONFORMÉIS",
      "frente a",
      "TRANSFORMAOS.",
      "“Conformarse” comunica la idea de adoptar el patrón de este siglo.",
      "El mundo constantemente intenta enseñarnos cómo pensar acerca del éxito, dinero, sexualidad,",
      "poder, relaciones, felicidad, venganza y nosotros mismos.",
      "Pablo llama al creyente a una manera diferente de pensar.",
      "La transformación ocurre mediante:",
      "“la renovación de vuestro entendimiento”.",
      "No se trata solamente de modificar comportamientos externos.",
      "El evangelio comienza a transformar cómo pensamos, y una nueva manera de pensar produce una",
      "nueva manera de vivir.",
      "Para reflexionar",
      "Compare estas maneras de pensar:",
      "Pensamiento de este sigloMente renovada",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 5",
      "“Primero yo.” ¿Cómo puedo servir?",
      "“Mi valor depende de mi posición.” Mi identidad está en Cristo.",
      "“Si me haces daño, te lo devuelvo.” No pagaré mal por mal.",
      "“Quiero ser reconocido.” Quiero honrar a otros.",
      "“Yo decido lo que está bien.” Quiero conocer lo que agrada a Dios.",
      "Pregunta personal",
      "¿Qué área de mi manera de pensar necesita ser confrontada por la Palabra de Dios?",
      "Verdad para recordar",
      "La verdadera adoración es responder a las misericordias de Dios entregándole toda",
      "nuestra vida.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 6",
      "Cristo en el centro",
      "Romanos 12 no es una lista de reglas para conseguir el favor de Dios. El capítulo comienza con las",
      "misericordias de Dios, conocidas supremamente en Jesucristo.",
      "Cristo se entregó por nosotros. Cristo sirvió con humildad. Cristo amó sin fingimiento. Cristo sufrió",
      "injustamente y venció el mal. Nuestra obediencia no reemplaza el evangelio: es el fruto del",
      "evangelio.",
      "Cristo se entregó para salvarnos; nosotros nos entregamos porque Él nos salvó.",
      "Respuesta personal",
      "¿Qué verdad de esta clase necesito creer con mayor profundidad?",
      "¿Qué cambio concreto demanda este pasaje de mí?",
      "¿Qué acción realizaré esta semana y cuándo la comenzaré?",
      "Oración",
      "Padre, gracias por tu misericordia manifestada en Jesucristo. Renueva mi mente y forma en mí una",
      "vida que responda a tu gracia con obediencia, humildad, servicio y amor. Ayúdame a vivir esta",
      "verdad durante la semana. En el nombre de Jesús. Amén."
    ]
  },
  {
    "slug": "clase-2",
    "label": "Clase 2",
    "title": "Una vida marcada por la humildad",
    "subtitle": "La gracia no nos da razones para sentirnos superiores; nos",
    "pdfUrl": "./files/romanos-12/02-una-vida-marcada-por-la-humildad.pdf",
    "paragraphs": [
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 1",
      "PRFWB",
      "ASOCIACIÓN BAUTISTA LIBRE DE PUERTO RICO",
      "UNA VIDA MARCADA POR LA",
      "HUMILDAD",
      "Romanos 12:3",
      "La gracia no nos da razones para sentirnos superiores; nos",
      "da razones para servir.",
      "Estudio individual ? Clase grupal ? Guía del estudiante",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 2",
      "TEXTO BASE Romanos 12:3",
      "OBJETIVO Aprender a evaluarnos correctamente a la luz de",
      "la gracia de Dios, evitando tanto el orgullo como",
      "la comparación.",
      "1. Lee y observa",
      "Lea Romanos 12:3.",
      "Busque dos ideas:",
      "Lo que no debemos hacer:",
      "“no tenga ______________________________”",
      "Lo que debemos hacer:",
      "“piense de sí ___________________________”",
      "Pregunta",
      "¿Está Pablo diciendo que debemos pensar que no tenemos ningún valor?",
      "No.",
      "Pablo no sustituye el orgullo con autodesprecio.",
      "Pide una evaluación sobria y correcta de nosotros mismos.",
      "2. El problema del orgullo",
      "El orgullo puede decir:",
      "“Soy mejor que ellos.”",
      "Pero también puede aparecer mediante comparación constante:",
      "“¿Por qué él tiene esa oportunidad y yo no?”",
      "“¿Por qué reconocieron a ella?”",
      "“Mi ministerio es más importante.”",
      "El contexto de los vv. 4–8 muestra por qué esto es especialmente peligroso dentro de la iglesia.",
      "Todo lo que poseemos para servir a Dios ha sido recibido por gracia.",
      "Por tanto:",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 3",
      "Un don nunca puede convertirse legítimamente en motivo de",
      "superioridad.",
      "3. ¿Qué significa “medida de fe”?",
      "La expresión ha recibido diferentes interpretaciones.",
      "Por eso debemos tener cuidado de no construir sobre ella conclusiones que el texto no establece",
      "claramente.",
      "Lo evidente en el contexto es el énfasis de Pablo:",
      "No pienses arrogantemente de ti mismo.",
      "Los versículos siguientes explicarán que existen diferentes miembros, funciones y dones, todos",
      "dentro de un mismo cuerpo y todos dependientes de la gracia.",
      "4. Examina tu corazón",
      "Considere estas situaciones:",
      "Cuando otra persona recibe reconocimiento…",
      "¿Me alegro o inmediatamente me comparo?",
      "Cuando alguien tiene una capacidad que yo no tengo…",
      "¿Doy gracias a Dios o siento envidia?",
      "Cuando Dios me utiliza…",
      "¿Pienso en su gracia o comienzo a sentirme superior?",
      "Cuando mi servicio pasa desapercibido…",
      "¿Continúo sirviendo?",
      "Escriba una oración breve pidiendo a Dios humildad:",
      "Cristo en este tema",
      "Lea Marcos 10:43.",
      "Jesús invierte la manera humana de entender la grandeza.",
      "En el reino de Dios, la grandeza no consiste en conseguir que otros nos sirvan.",
      "La grandeza se expresa mediante el servicio.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 4",
      "Cristo mismo es nuestro modelo supremo de humildad y servicio.",
      "Verdad para recordar",
      "La gracia no nos da razones para sentirnos superiores; nos da razones para servir.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 5",
      "Cristo en el centro",
      "Romanos 12 no es una lista de reglas para conseguir el favor de Dios. El capítulo comienza con las",
      "misericordias de Dios, conocidas supremamente en Jesucristo.",
      "Cristo se entregó por nosotros. Cristo sirvió con humildad. Cristo amó sin fingimiento. Cristo sufrió",
      "injustamente y venció el mal. Nuestra obediencia no reemplaza el evangelio: es el fruto del",
      "evangelio.",
      "Cristo se entregó para salvarnos; nosotros nos entregamos porque Él nos salvó.",
      "Respuesta personal",
      "¿Qué verdad de esta clase necesito creer con mayor profundidad?",
      "¿Qué cambio concreto demanda este pasaje de mí?",
      "¿Qué acción realizaré esta semana y cuándo la comenzaré?",
      "Oración",
      "Padre, gracias por tu misericordia manifestada en Jesucristo. Renueva mi mente y forma en mí una",
      "vida que responda a tu gracia con obediencia, humildad, servicio y amor. Ayúdame a vivir esta",
      "verdad durante la semana. En el nombre de Jesús. Amén."
    ]
  },
  {
    "slug": "clase-3",
    "label": "Clase 3",
    "title": "Una vida al servicio del cuerpo",
    "subtitle": "Los dones son expresiones de la gracia de Dios para servir a",
    "pdfUrl": "./files/romanos-12/03-una-vida-al-servicio-del-cuerpo.pdf",
    "paragraphs": [
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 1",
      "PRFWB",
      "ASOCIACIÓN BAUTISTA LIBRE DE PUERTO RICO",
      "UNA VIDA AL SERVICIO DEL",
      "CUERPO",
      "Romanos 12:4–8",
      "Los dones son expresiones de la gracia de Dios para servir a",
      "otros.",
      "Estudio individual ? Clase grupal ? Guía del estudiante",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 2",
      "TEXTO BASE Romanos 12:4–8",
      "OBJETIVO Comprender que Dios concede diferentes dones",
      "para servir al cuerpo de Cristo y no para",
      "competir por importancia.",
      "1. La ilustración del cuerpo",
      "Lea Romanos 12:4–5.",
      "Pablo utiliza algo que todos conocemos:",
      "EL CUERPO HUMANO.",
      "Un cuerpo posee muchas partes.",
      "Pero no todas realizan la misma función.",
      "Ahora Pablo aplica la ilustración a la iglesia:",
      "MUCHOS MIEMBROS",
      "↓",
      "DIFERENTES FUNCIONES",
      "↓",
      "UN CUERPO EN CRISTO",
      "La diversidad no es un problema que debemos eliminar.",
      "Es parte del diseño de Dios.",
      "2. Nos necesitamos unos a otros",
      "Romanos 12:5 contiene una expresión importante:",
      "“miembros los unos de los otros”.",
      "El cristianismo bíblico no es individualista.",
      "No solamente pertenecemos a Cristo.",
      "En Cristo hemos sido unidos a un cuerpo.",
      "Esto significa que necesitamos a creyentes diferentes de nosotros.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 3",
      "Para discutir o reflexionar",
      "¿Qué ocurriría en una iglesia donde todos quisieran enseñar, pero nadie quisiera servir?",
      "¿Qué ocurriría si todos quisieran dirigir?",
      "¿Por qué necesitamos diferentes capacidades?",
      "3. Dones según la gracia",
      "Lea Romanos 12:6.",
      "Observe:",
      "“diferentes dones”",
      "y:",
      "“según la gracia que nos es dada”.",
      "Podemos resumirlo:",
      "GRACIA → DON → SERVICIO",
      "El don comienza con Dios, no con nosotros.",
      "4. Los dones mencionados",
      "Romanos 12:6–8 menciona diferentes formas de servicio.",
      "Profecía",
      "Debe ejercerse conforme a lo establecido por Dios, no como plataforma para engrandecer al",
      "mensajero.",
      "Servicio",
      "Quien ha recibido capacidad para servir debe dedicarse a servir.",
      "Mucho ministerio cristiano ocurre sin plataforma ni reconocimiento público.",
      "Enseñanza",
      "Quien enseña debe dedicarse fielmente a comunicar la verdad.",
      "Compare con Hechos 6:4, donde encontramos el compromiso con la oración y el ministerio de la",
      "Palabra.",
      "Exhortación",
      "Incluye animar, fortalecer y llamar a otros a perseverar en el camino correcto.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 4",
      "Dar",
      "Debe hacerse con generosidad.",
      "Liderazgo",
      "Debe ejercerse con diligencia.",
      "El liderazgo cristiano implica responsabilidad, no simplemente autoridad.",
      "Misericordia",
      "Debe practicarse con alegría.",
      "5. Una pregunta diferente sobre los dones",
      "Es común preguntar:",
      "“¿Cuál es mi don?”",
      "Es una pregunta válida.",
      "Pero Romanos 12 nos lleva a otra:",
      "“¿A quién estoy sirviendo con lo que Dios me dio?”",
      "Complete:",
      "Una capacidad que Dios me ha dado:",
      "Una necesidad que puedo ayudar a suplir:",
      "Una acción concreta que puedo realizar:",
      "Para profundizar",
      "Lea:",
      "Efesios 4:11–12",
      "1 Pedro 4:10–11",
      "Marcos 10:43",
      "Mientras lee, pregunte:",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 5",
      "¿Para beneficio de quién deben utilizarse los dones?",
      "Verdad para recordar",
      "Los dones espirituales no son trofeos para demostrar importancia; son expresiones",
      "de la gracia de Dios para servir a otros.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 6",
      "Cristo en el centro",
      "Romanos 12 no es una lista de reglas para conseguir el favor de Dios. El capítulo comienza con las",
      "misericordias de Dios, conocidas supremamente en Jesucristo.",
      "Cristo se entregó por nosotros. Cristo sirvió con humildad. Cristo amó sin fingimiento. Cristo sufrió",
      "injustamente y venció el mal. Nuestra obediencia no reemplaza el evangelio: es el fruto del",
      "evangelio.",
      "Cristo se entregó para salvarnos; nosotros nos entregamos porque Él nos salvó.",
      "Respuesta personal",
      "¿Qué verdad de esta clase necesito creer con mayor profundidad?",
      "¿Qué cambio concreto demanda este pasaje de mí?",
      "¿Qué acción realizaré esta semana y cuándo la comenzaré?",
      "Oración",
      "Padre, gracias por tu misericordia manifestada en Jesucristo. Renueva mi mente y forma en mí una",
      "vida que responda a tu gracia con obediencia, humildad, servicio y amor. Ayúdame a vivir esta",
      "verdad durante la semana. En el nombre de Jesús. Amén."
    ]
  },
  {
    "slug": "clase-4",
    "label": "Clase 4",
    "title": "Una vida de amor genuino",
    "subtitle": "El amor transformado por el evangelio se demuestra en la",
    "pdfUrl": "./files/romanos-12/04-una-vida-de-amor-genuino.pdf",
    "paragraphs": [
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 1",
      "PRFWB",
      "ASOCIACIÓN BAUTISTA LIBRE DE PUERTO RICO",
      "UNA VIDA DE AMOR GENUINO",
      "Romanos 12:9–16",
      "El amor transformado por el evangelio se demuestra en la",
      "manera en que tratamos a las personas.",
      "Estudio individual ? Clase grupal ? Guía del estudiante",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 2",
      "TEXTO BASE Romanos 12:9–16",
      "OBJETIVO Identificar las características concretas del amor",
      "que produce una vida transformada por el",
      "evangelio.",
      "1. La frase que gobierna la sección",
      "Lea Romanos 12:9.",
      "“El amor sea sin fingimiento.”",
      "Pablo no quiere una apariencia de amor.",
      "Quiere amor verdadero.",
      "Inmediatamente añade:",
      "“Aborreced lo malo, seguid lo bueno.”",
      "Esto enseña algo importante.",
      "Amor no significa aprobar todo.",
      "El amor bíblico puede distinguir entre el bien y el mal.",
      "2. Busque las marcas del amor",
      "Lea Romanos 12:9–13 y complete:",
      "En cuanto al mal: ___________________________",
      "En cuanto al bien: __________________________",
      "En cuanto a los hermanos: ___________________",
      "En cuanto a la honra: _______________________",
      "En cuanto al servicio: ______________________",
      "En la esperanza: ____________________________",
      "En la tribulación: __________________________",
      "En la oración: ______________________________",
      "Ante las necesidades: _______________________",
      "En cuanto a hospitalidad: ___________________",
      "Observe lo práctico del pasaje.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 3",
      "El amor cristiano no permanece como sentimiento abstracto.",
      "Actúa.",
      "3. Cuando otro se alegra",
      "Romanos 12:15 dice:",
      "“Gozaos con los que se gozan.”",
      "Parece sencillo hasta que otra persona recibe exactamente aquello que nosotros deseábamos.",
      "Un ascenso.",
      "Una oportunidad.",
      "Reconocimiento.",
      "Una bendición.",
      "Entonces aparece nuevamente el problema del v. 3:",
      "el orgullo y la comparación.",
      "El amor verdadero puede celebrar la bendición de otro sin convertirla en una evaluación de",
      "nuestro propio valor.",
      "4. Cuando otro llora",
      "Pablo continúa:",
      "“llorad con los que lloran.”",
      "No siempre necesitamos tener una explicación para el sufrimiento de otra persona.",
      "A veces el amor simplemente se acerca y acompaña.",
      "Reflexiona",
      "Cuando alguien comparte conmigo su dolor, ¿escucho o inmediatamente intento solucionar el",
      "problema?",
      "5. Bendecir al perseguidor",
      "Romanos 12:14 eleva considerablemente la exigencia:",
      "“Bendecid a los que os persiguen.”",
      "Pablo no dice simplemente:",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 4",
      "“Toléralos.”",
      "El creyente es llamado a responder de una manera radicalmente diferente.",
      "Esto prepara el camino para los vv. 17–21.",
      "6. Humildad otra vez",
      "Romanos 12:16 regresa al problema del orgullo:",
      "“no altivos”",
      "y:",
      "“No seáis sabios en vuestra propia opinión.”",
      "Observe la conexión:",
      "v. 3 — No tengas un concepto exagerado de ti.",
      "v. 16 — No seas sabio en tu propia opinión.",
      "La humildad atraviesa todo el capítulo.",
      "Autoevaluación",
      "De las siguientes características, marque aquella en la que más necesita crecer:",
      "Amor genuino☐",
      "Rechazar el mal☐",
      "Honrar a otros☐",
      "Diligencia☐",
      "Servicio☐",
      "Esperanza☐",
      "Paciencia☐",
      "Oración☐",
      "Generosidad☐",
      "Hospitalidad☐",
      "Empatía☐",
      "Humildad☐",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 5",
      "¿Qué acción concreta puedes tomar esta semana?",
      "Verdad para recordar",
      "El amor transformado por el evangelio no es solamente algo que sentimos; se",
      "demuestra en la manera en que tratamos a las personas.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 6",
      "Cristo en el centro",
      "Romanos 12 no es una lista de reglas para conseguir el favor de Dios. El capítulo comienza con las",
      "misericordias de Dios, conocidas supremamente en Jesucristo.",
      "Cristo se entregó por nosotros. Cristo sirvió con humildad. Cristo amó sin fingimiento. Cristo sufrió",
      "injustamente y venció el mal. Nuestra obediencia no reemplaza el evangelio: es el fruto del",
      "evangelio.",
      "Cristo se entregó para salvarnos; nosotros nos entregamos porque Él nos salvó.",
      "Respuesta personal",
      "¿Qué verdad de esta clase necesito creer con mayor profundidad?",
      "¿Qué cambio concreto demanda este pasaje de mí?",
      "¿Qué acción realizaré esta semana y cuándo la comenzaré?",
      "Oración",
      "Padre, gracias por tu misericordia manifestada en Jesucristo. Renueva mi mente y forma en mí una",
      "vida que responda a tu gracia con obediencia, humildad, servicio y amor. Ayúdame a vivir esta",
      "verdad durante la semana. En el nombre de Jesús. Amén."
    ]
  },
  {
    "slug": "clase-5",
    "label": "Clase 5",
    "title": "Una vida que vence el mal con el bien",
    "subtitle": "No seas vencido de lo malo, sino vence con el bien el mal.",
    "pdfUrl": "./files/romanos-12/05-una-vida-que-vence-el-mal-con-el-bien.pdf",
    "paragraphs": [
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 1",
      "PRFWB",
      "ASOCIACIÓN BAUTISTA LIBRE DE PUERTO RICO",
      "UNA VIDA QUE VENCE EL MAL",
      "CON EL BIEN",
      "Romanos 12:17–21",
      "No seas vencido de lo malo, sino vence con el bien el mal.",
      "Estudio individual ? Clase grupal ? Guía del estudiante",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 2",
      "TEXTO BASE Romanos 12:17–21",
      "OBJETIVO Aprender cómo responde el discípulo de Cristo",
      "ante la ofensa, la injusticia y el deseo de",
      "venganza.",
      "1. Lee el pasaje completo",
      "Lea Romanos 12:17–21 sin detenerse.",
      "Ahora identifique cada aparición de:",
      "MAL",
      "BIEN",
      "PAZ",
      "VENGANZA",
      "ENEMIGO",
      "¿Cuál parece ser el gran conflicto de esta sección?",
      "2. El ciclo del mal",
      "Romanos 12:17 dice:",
      "“No paguéis a nadie mal por mal.”",
      "Imagine esta secuencia:",
      "Me hieren",
      "↓",
      "Yo respondo hiriendo",
      "↓",
      "La otra persona responde",
      "↓",
      "Yo vuelvo a responder",
      "↓",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 3",
      "EL MAL SE MULTIPLICA.",
      "Pablo quiere romper el ciclo.",
      "Pero no lo hace fingiendo que la injusticia no ocurrió.",
      "Presenta otra respuesta.",
      "3. Buscar la paz",
      "Lea Romanos 12:18 cuidadosamente.",
      "Observe dos condiciones:",
      "“Si es posible…”",
      "“en cuanto dependa de vosotros…”",
      "Esto significa que no podemos controlar la respuesta de todas las personas.",
      "Pero sí somos responsables de nuestra propia conducta.",
      "Pregunta personal",
      "En un conflicto actual o pasado:",
      "¿He hecho lo que bíblicamente depende de mí para buscar la paz?",
      "4. ¿Por qué no vengarnos?",
      "Lea Romanos 12:19.",
      "La respuesta no es:",
      "“Porque la injusticia no importa.”",
      "La respuesta es:",
      "Porque Dios es Juez.",
      "Pablo cita la declaración:",
      "“Mía es la venganza, yo pagaré, dice el Señor.”",
      "Renunciar a la venganza significa reconocer:",
      "No soy el juez final. Dios lo es.",
      "Esto requiere fe.",
      "Tenemos que confiar en que Dios ve perfectamente aquello que nosotros vemos parcialmente.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 4",
      "5. ¿Qué hago entonces con mi enemigo?",
      "Romanos 12:20 lleva la enseñanza todavía más lejos.",
      "Si tiene hambre:",
      "dale de comer.",
      "Si tiene sed:",
      "dale de beber.",
      "Pablo cita aquí Proverbios 25:21–22.",
      "Observe la progresión:",
      "No vengarte es una cosa.",
      "Hacer bien a quien te hizo mal va todavía más lejos.",
      "Ese es el carácter radical del amor cristiano.",
      "6. El gran final de Romanos 12",
      "Lea Romanos 12:21.",
      "“No seas vencido de lo malo, sino vence con el bien el mal.”",
      "Este versículo resume extraordinariamente la sección.",
      "Existen dos posibilidades:",
      "EL MAL ME VENCE",
      "Recibo mal y me convierto en alguien que también hace mal.",
      "O:",
      "VENZO EL MAL CON EL BIEN",
      "No permito que el pecado de otra persona determine mi obediencia a Dios.",
      "7. Regrese ahora a Romanos 12:2",
      "Al principio estudiamos:",
      "“No os conforméis…”",
      "Ahora vemos cómo luce una mente renovada.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 5",
      "El mundo puede decir:",
      "“Véngate.”",
      "La mente renovada dice:",
      "“Confío en la justicia de Dios.”",
      "El mundo:",
      "“Devuélvele lo mismo.”",
      "La mente renovada:",
      "“No pagaré mal por mal.”",
      "El mundo:",
      "“Destruye a tu enemigo.”",
      "El evangelio:",
      "“Si tiene hambre, dale de comer.”",
      "Ahora podemos ver que Romanos 12:2 y Romanos 12:21 están profundamente relacionados.",
      "PRFWB | FORMACIÓN BÍBLICA",
      "Romanos 12 ? Una vida transformada por las misericordias de Dios ? 6",
      "Cristo en el centro",
      "Romanos 12 no es una lista de reglas para conseguir el favor de Dios. El capítulo comienza con las",
      "misericordias de Dios, conocidas supremamente en Jesucristo.",
      "Cristo se entregó por nosotros. Cristo sirvió con humildad. Cristo amó sin fingimiento. Cristo sufrió",
      "injustamente y venció el mal. Nuestra obediencia no reemplaza el evangelio: es el fruto del",
      "evangelio.",
      "Cristo se entregó para salvarnos; nosotros nos entregamos porque Él nos salvó.",
      "Respuesta personal",
      "¿Qué verdad de esta clase necesito creer con mayor profundidad?",
      "¿Qué cambio concreto demanda este pasaje de mí?",
      "¿Qué acción realizaré esta semana y cuándo la comenzaré?",
      "Oración",
      "Padre, gracias por tu misericordia manifestada en Jesucristo. Renueva mi mente y forma en mí una",
      "vida que responda a tu gracia con obediencia, humildad, servicio y amor. Ayúdame a vivir esta",
      "verdad durante la semana. En el nombre de Jesús. Amén."
    ]
  }
];
