import { Resource } from './types';

export const initialResources: Resource[] = [
  {
    id: '1',
    title: 'Fundamentos del discipulado',
    description: 'Guía breve para nuevas personas en su proceso de crecimiento espiritual.',
    category: 'Nuevo creyente',
    type: 'document',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    fileUrl: 'https://example.com/discipulado.pdf',
    author: 'Ministerio de discípulos',
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-07-01',
    displayOrder: 1,
  },
  {
    id: '2',
    title: 'Oración y silencio espiritual',
    description: 'Devocional para profundizar en la práctica de la oración diaria.',
    category: 'Oración',
    type: 'devotional',
    imageUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=900&q=80',
    externalUrl: 'https://example.com/oracion',
    author: 'Equipo pastoral',
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-07-08',
    displayOrder: 2,
  },
  {
    id: '3',
    title: 'Estudio bíblico: Vida en comunidad',
    description: 'Serie de estudio para líderes y grupos pequeños.',
    category: 'Estudios bíblicos',
    type: 'study',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=80',
    externalUrl: 'https://youtube.com/watch?v=example',
    author: 'Pastor Javier',
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-07-12',
    displayOrder: 3,
  },
  {
    id: '4',
    title: 'Guía para líderes jóvenes',
    description: 'Curso práctico orientado a liderazgo y acompañamiento.',
    category: 'Liderazgo',
    type: 'course',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
    fileUrl: 'https://example.com/liderazgo.pdf',
    author: 'Academia de líderes',
    isPublished: false,
    isFeatured: false,
    createdAt: '2026-07-14',
    displayOrder: 4,
  },
];

export const categoryOptions = [
  'Nuevo creyente',
  'Discipulado',
  'Bautistas Libres',
  'Estudios bíblicos',
  'Oración',
  'Devocionales',
  'Familia',
  'Jóvenes',
  'Niños',
  'Liderazgo',
  'Recursos para líderes',
  'Predicaciones',
  'Multimedia',
];

export const typeOptions = ['pdf', 'video', 'audio', 'link', 'study', 'devotional', 'course', 'document'];
